CREATE TABLE TECLADO(
    id_producto                             NUMBER(3) NOT NULL,
    NOMBRE_PRODUCTO                         VARCHAR2(50) NOT NULL,
    ID_PROVEEDOR                            NUMBER(3) NOT NULL,
    PRECIO                                  NUMBER NOT NULL,
    STOCK                                   NUMBER NOT NULL,
    CONSTRAINT PK_TECLADO                   PRIMARY KEY(id_producto)
);

CREATE TABLE MONITOR(
    id_producto                             NUMBER(3) NOT NULL,
    NOMBRE_PRODUCTO                         VARCHAR2(50) NOT NULL,
    ID_PROVEEDOR                            NUMBER(3) NOT NULL,
    PRECIO                                  NUMBER NOT NULL,
    STOCK                                   NUMBER NOT NULL,
    CONSTRAINT PK_MONITOR                   PRIMARY KEY(id_producto)
);


CREATE TABLE PROCESADOR(
    id_producto                             NUMBER(3) NOT NULL,
    NOMBRE_PRODUCTO                         VARCHAR2(50) NOT NULL,
    ID_PROVEEDOR                            NUMBER(3) NOT NULL,
    PRECIO                                  NUMBER NOT NULL,
    STOCK                                   NUMBER NOT NULL,
    CONSTRAINT PK_PROCESADOR                PRIMARY KEY(id_producto)   
);

CREATE TABLE USUARIO(
    ID_USUARIO                              NUMBER(3) NOT NULL,
    NOMBRE_USUARIO                          VARCHAR2(50) NOT NULL,
    CORREO_USUARIO                          VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_USUARIO                   PRIMARY KEY(ID_USUARIO)       
);


CREATE TABLE RAM(
    ID_RAM                                  NUMBER(3)   NOT NULL,
    CAPACIDAD_RAM                           NUMBER(6)   NOT NULL,
    TIPO_RAM                                VARCHAR(5)  NOT NULL,
    FRECUENCIA_RAM                          NUMBER(6)   NOT NULL,
    FORMATO_RAM                             VARCHAR(20) NOT NULL,
    ID_PROVEEDOR                            NUMBER(3)   NOT NULL,
    CONSTRAINT PK_RAM                       PRIMARY KEY(ID_RAM)
   
);

CREATE TABLE MOUSE(
    ID_MOUSE                                NUMBER(3)    NOT NULL,
    NOMBRE_MOUSE                            VARCHAR2(50) NOT NULL,
    DPI_MOUSE                               NUMBER(6)    NOT NULL,
    ID_PROVEEDOR                            NUMBER(3)    NOT NULL,
    CONSTRAINT PK_MOUSE                      PRIMARY KEY(ID_MOUSE)
   
);


CREATE TABLE AUDIFONO(
    ID_AUDIFONO                             NUMBER(3) NOT NULL,
    NOMBRE_PRODUCTO                         VARCHAR2(50),
    ID_PROVEEDOR                            NUMBER(3),
    PRECIO                                  NUMBER,
    STOCK                                   NUMBER,
    CONSTRAINT PK_AUDIFONO                  PRIMARY KEY(ID_AUDIFONO)
);

CREATE TABLE GABINETE(
    ID_GABINETE                             NUMBER(3) NOT NULL,
    NOMBRE_PRODUCTO                         VARCHAR2(50),
    ID_PROVEEDOR                            NUMBER(3) NOT NULL,
    PRECIO                                  NUMBER,
    STOCK                                   NUMBER,
    CONSTRAINT PK_GABINETE                  PRIMARY KEY(ID_GABINETE)
);

CREATE TABLE ACCESORIO( 
    ID_ACCESORIO                            NUMBER(3) NOT NULL,
    NOMBRE_ACCESORIO                        VARCHAR2(50),
    PRECIO                                  NUMBER,
    STOCK                                   NUMBER,
    ID_PROVEEDOR                            NUMBER(3) NOT NULL,
    CONSTRAINT PK_ACCESORIO                 PRIMARY KEY(ID_ACCESORIO)
);

CREATE TABLE ALMACENAMIENTO(
    ID_ALMACENAMIENTO                      NUMBER(3) NOT NULL,
    NOMBRE_PRODUCTO                         VARCHAR2(50),
    ID_PROVEEDOR                            NUMBER(3),
    PRECIO                                  NUMBER,
    STOCK                                   NUMBER,
    CONSTRAINT PK_ALMACENAMIENTO            PRIMARY KEY(ID_ALMACENAMIENTO )
);

CREATE TABLE PAIS(
    ID_PAIS                                 NUMBER NOT NULL,
    PAIS                                    VARCHAR2(50),

    CONSTRAINT PK_PAIS PRIMARY KEY (ID_PAIS)
);

CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR                            NUMBER(3) NOT NULL,
    NOMBRE_PROVEEDOR                        VARCHAR2(50),
    ID_PAIS                                 NUMBER(3) NOT NULL,

    CONSTRAINT  PK_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR)
);

CREATE TABLE GPU(
    ID_GPU                                  NUMBER(3) NOT NULL,
    NOMBRE_PRODUCTO                         VARCHAR2(50),
    ID_PROVEEDOR                            NUMBER(3),
    PRECIO                                  NUMBER,
    STOCK                                   NUMBER,

    CONSTRAINT PK_GPU PRIMARY KEY (ID_GPU)
);

CREATE TABLE OFERTA(
    ID_OFERTA                               NUMBER(3) NOT NULL,
    PORCE_OFERTA                            NUMBER(3) NOT NULL,

    CONSTRAINT PK_OFERTA PRIMARY KEY (ID_OFERTA)
);



CREATE TABLE COMPRA(
    ID_COMPRA                               NUMBER(3) NOT NULL,
    ID_USUARIO                              NUMBER(3) NOT NULL,    
    ID_TECLADO                              NUMBER(3) NOT NULL,
    ID_MONITOR                              NUMBER(3) NOT NULL,
    ID_PROCESADOR                           NUMBER(3) NOT NULL,
    ID_RAM                                  NUMBER(3) NOT NULL,
    ID_AUDIFONO                             NUMBER(3) NOT NULL,
    ID_GABINETE                             NUMBER(3) NOT NULL,
    ID_ACCESORIO                            NUMBER(3) NOT NULL,
    ID_GPU                                  NUMBER(3) NOT NULL,
    ID_ALMACENAMIENTO                       NUMBER(3) NOT NULL,
    
    CONSTRAINT PK_COMPRA PRIMARY KEY (ID_COMPRA)   
);

CREATE TABLE CARRITO(
    ID_CARRITO                              NUMBER(3) NOT NULL,
    ID_COMPRA                               NUMBER(3) NOT NULL,

    CONSTRAINT PK_CARRITO PRIMARY KEY(ID_CARRITO)
);

CREATE TABLE COMENTARIO(
    ID_COMENTARIO                           NUMBER(3) NOT NULL,
    ID_USUARIO                              NUMBER(3) NOT NULL,
    CREATED_AT                              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COMENTARIO                              VARCHAR2(252),
    
    CONSTRAINT PK_COMENTARIO PRIMARY KEY (ID_COMENTARIO)
);


-- Creacion de constraints de primary & foreign keys


     
ALTER TABLE TECLADO
    ADD CONSTRAINT TECLADO_FK
     FOREIGN KEY  (ID_PROVEEDOR)  REFERENCES PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE MOUSE
    ADD CONSTRAINT MOUSE_FK
     FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);
     
ALTER TABLE AUDIFONO
    ADD CONSTRAINT AUDIFONO_FK
     FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE RAM
    ADD CONSTRAINT RAM_FK
     FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE MONITOR
    ADD CONSTRAINT MONITOR_FK
     FOREIGN KEY  (ID_PROVEEDOR)  REFERENCES PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE PROCESADOR
    ADD CONSTRAINT PROCESADOR_FK
     FOREIGN KEY  (ID_PROVEEDOR)  REFERENCES PROVEEDOR(ID_PROVEEDOR);
     

ALTER TABLE GABINETE
    ADD CONSTRAINT GABINETE_FK
     FOREIGN KEY  (ID_PROVEEDOR)  REFERENCES PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE ACCESORIO
    ADD CONSTRAINT ACCESORIO_FK
     FOREIGN KEY  (ID_PROVEEDOR)  REFERENCES PROVEEDOR(ID_PROVEEDOR);

ALTER TABLE ALMACENAMIENTO
    ADD CONSTRAINT ALMACENAMIENTO_FK
     FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);
     
ALTER TABLE PROVEEDOR
    ADD CONSTRAINT PROVEEDOR_FK
     FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS);    

ALTER TABLE GPU
    ADD CONSTRAINT GPU_FK
     FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR);


ALTER TABLE COMPRA
    ADD CONSTRAINT USUARIO_FK_COMPRA
     FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE COMPRA
    ADD CONSTRAINT TECLADO_FK_COMPRA
     FOREIGN KEY (ID_TECLADO) REFERENCES TECLADO(ID_PRODUCTO);
ALTER TABLE COMPRA
    ADD CONSTRAINT MONITOR_FK_COMPRA
     FOREIGN KEY (ID_MONITOR) REFERENCES MONITOR(ID_PRODUCTO);
ALTER TABLE COMPRA
    ADD CONSTRAINT PROCESADOR_FK_COMPRA
     FOREIGN KEY (ID_PROCESADOR) REFERENCES PROCESADOR(ID_PRODUCTO);
ALTER TABLE COMPRA
    ADD CONSTRAINT RAM_FK_COMPRA
     FOREIGN KEY (ID_RAM) REFERENCES RAM(ID_RAM);
ALTER TABLE COMPRA
    ADD CONSTRAINT AUDIFONO_FK_COMPRA
     FOREIGN KEY (ID_AUDIFONO) REFERENCES AUDIFONO(ID_AUDIFONO);
ALTER TABLE COMPRA
    ADD CONSTRAINT GABINETE_FK_COMPRA 
     FOREIGN KEY (ID_GABINETE) REFERENCES GABINETE(ID_GABINETE);
ALTER TABLE COMPRA
    ADD CONSTRAINT ACCESORIO_FK_COMPRA
     FOREIGN KEY (ID_ACCESORIO) REFERENCES ACCESORIO(ID_ACCESORIO);
ALTER TABLE COMPRA
    ADD CONSTRAINT GPU_FK_COMPRA
     FOREIGN KEY (ID_GPU) REFERENCES GPU(ID_GPU);
ALTER TABLE COMPRA
    ADD CONSTRAINT ALMACENAMIENTO_FK_COMPRA
     FOREIGN KEY (ID_ALMACENAMIENTO) REFERENCES ALMACENAMIENTO(ID_ALMACENAMIENTO);

ALTER TABLE CARRITO
    ADD CONSTRAINT COMPRA_FK_CARRITO
     FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID_COMPRA);

ALTER TABLE COMENTARIO
    ADD CONSTRAINT USUARIO_FK_COMENTARIO
     FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);


--INICIO DE LOS INSERT!



--  INSERT PAIS

INSERT INTO PAIS VALUES(1, 'CHILE');
INSERT INTO PAIS VALUES(2, 'ESTADOS UNIDOS');



-- INSERT PROVEEDOR

INSERT INTO PROVEEDOR VALUES(1, 'RAZER', 2);
INSERT INTO PROVEEDOR VALUES(2, 'LOGITECH', 2);
INSERT INTO PROVEEDOR VALUES(3, 'REDRAGON', 2);
INSERT INTO PROVEEDOR VALUES(4, 'HYPERX', 2);
INSERT INTO PROVEEDOR VALUES(5, 'COOLERMASTER', 2);


-- INSERT MOUSE

-- INSERT INTO MOUSE VALUES(1, 'DEATHEADDER V2 WIRELESS', 25000)


     
         

    

    
    
    
    
    




    
    




    

    

    